slurmstepd: error: execve(): source: No such file or directory
slurmstepd: error: execve(): source: No such file or directory
slurmstepd: error: execve(): source: No such file or directory
slurmstepd: error: execve(): source: No such file or directory
srun: error: spartan-gpgpu012: tasks 0-3: Exited with exit code 2
Traceback (most recent call last):
  File "pretrained_main.py", line 486, in <module>
    main()
  File "pretrained_main.py", line 108, in main
    args.world_size = int(os.environ["WORLD_SIZE"])
  File "/home/junzhin/anaconda3/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'WORLD_SIZE'
Traceback (most recent call last):
  File "pretrained_main.py", line 486, in <module>
    main()
  File "pretrained_main.py", line 108, in main
    args.world_size = int(os.environ["WORLD_SIZE"])
  File "/home/junzhin/anaconda3/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'WORLD_SIZE'
Traceback (most recent call last):
  File "pretrained_main.py", line 486, in <module>
    main()
  File "pretrained_main.py", line 108, in main
    args.world_size = int(os.environ["WORLD_SIZE"])
  File "/home/junzhin/anaconda3/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'WORLD_SIZE'
Traceback (most recent call last):
  File "pretrained_main.py", line 486, in <module>
    main()
  File "pretrained_main.py", line 108, in main
    args.world_size = int(os.environ["WORLD_SIZE"])
  File "/home/junzhin/anaconda3/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'WORLD_SIZE'
srun: error: spartan-gpgpu012: tasks 0-3: Exited with exit code 1
